include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - _archive/**
    - _backup/**
    - backup_*/**
    - _hotfix_*/**
    - _patch*/**
    - "*_patch*.*"
    - lib/**/_archive/**
    - lib/**/_backup/**
    - lib/**/backup_*/**
    - lib/**/_hotfix_*/**
    - lib/**/_patch*/**
    - lib/**/_patch*/**
    - "**/*.g.dart"
    - "build/**"
    - ".dart_tool/**"
