workflows:
  takimaki-android:
    name: Takimaki Android Build
    max_build_duration: 60
    environment:
      flutter: stable
      java: 17
    cache:
      cache_paths:
        - C:\Users\bokat/.pub-cache
        - C:\Users\bokat/.gradle/caches
    scripts:
      - name: Get Flutter dependencies
        script: flutter pub get
      - name: Build release APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
