workflows:
  takimaki-android:
    name: Takimaki Android Build
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Pre-build cleanup
        script: |
          set -e
          flutter clean
          dart pub cache clean || true
          flutter pub get --suppress-analytics
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
