name: takimaki_full
description: Takimaki mobile app
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  intl: 0.20.2
  cupertino_icons: ^1.0.6
  google_maps_flutter: ^2.12.3
  shared_preferences: ^2.5.3
  sms_autofill: ^2.3.0
  image_picker: 1.1.2
  table_calendar: ^3.2.0
  geocoding: ^4.0.0
  google_place: ^0.4.7
  firebase_core: ^3.15.0
  firebase_auth: 5.2.0
  firebase_storage: 12.3.0
  cached_network_image: 3.3.1
  cloud_firestore: ^5.4.4

dev_dependencies:
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/takimaki_icon.png

flutter_icons:
  android: true
  ios: true
  image_path: assets/icons/takimaki_icon.png
  remove_alpha_ios: true
