name: takimaki_full
description: Takimaki mobile app
publish_to: "none"

version: 1.0.18+19

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.5.5
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/takimaki_icon.png
    - assets/icons/takimaki_icon_legacy.png
    - assets/icons/takimaki_icon_foreground.png
    - assets/images/takimaki_mascot.png
    - assets/service_icons/
    - assets/services.json

flutter_icons:
  android: true
  ios: true
  image_path: assets/icons/takimaki_icon_legacy.png
  adaptive_icon_background: "#087B7B"
  adaptive_icon_foreground: assets/icons/takimaki_icon_foreground.png
  adaptive_icon_foreground_inset: 0
  remove_alpha_ios: true
